; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 1.0m
; need this build flag if we're using FreeRTOS
build_flags =
	-DPIO_FRAMEWORK_ARDUINO_ENABLE_FREERTOS
	-DBUILD_TIMESTAMP=$UNIX_TIME
; change MCU frequency
extra_scripts = 
	pre:buildscript_versioning.py
lib_deps = 
	https://github.com/waspinator/AccelStepper
	https://github.com/I-AM-ENGINEER/MT6701-arduino
	https://github.com/eecharlie/MatrixMath
